spring:
    profiles:
        active :
        - dev
---
spring:
     profiles: dev    #开发环境1
     application:
         name: microservicecloud-config-atguigu-dev
---
spring:
      profiles: test  #测试环境2
      application: 
             name: microservicecloud-config-atguigu-test

